kind: pipeline
name: default

auth: &auth
    username:
        from_secret: dockerhub_username
    password:
        from_secret: dockerhub_password

repo: &repo
    repo: maxkratz/postfix

steps:
  - name: docker
    image: plugins/docker
    settings:
        dockerfile: Dockerfile
        <<: *repo
        tags:
            - latest
        <<: *auth
    when:
        branch:
            - main
